### ISSUE TITLE
開発手順実行中のエラー

### ISSUE THREAD

**Issue by ghost** [ITS-CDA-Core/docs#2]
開発手順のvagrant upを行ったところ、以下のエラーが出ました。
まだちゃんと調べてないのですが、まず進捗報告も兼ねて、投稿させてもらいました。

以下はエラーログの一部です。
Spring-frameworkのjarをインストールしている際にエラーが発生したようです。

![2015-05-09 9 31 42](https://cloud.githubusercontent.com/assets/12036877/7547749/82a9ca62-f62e-11e4-87dc-c4486d706fe5.png)
![2015-05-09 9 32 53](https://cloud.githubusercontent.com/assets/12036877/7547754/89f50be2-f62e-11e4-8eaf-397b02835f70.png)

エラーが出てもvagrant upの実行は終了し、vagrant statusを実行するとRunningと出るため、
仮想環境自体は動いてるようです。

エラーについてはまた調べます。
取り急ぎ、報告まで。

**Comment by imaizm** [comment]
吉川さん

お疲れ様です。今泉です。

当件、個別解決策ではありませんが、一度以下を試してもらえますでしょうか。

①GitHub Clientにて、「workshop_FY15」を選択の上、右上の「Sync」ボタンをクリック
![_2015-05-09_10_01_44](https://cloud.githubusercontent.com/assets/18225/7547946/349c0e2a-f633-11e4-8c24-f994b04bba9d.jpg)

②コマンドプロンプト／ターミナルにて、Vagrantfileが配置されているフォルダに移動し、
　「vagrant destroy」を実行。

③②の実行が終わったら、改めて「vagrant up」を実施

上記、よろしくお願いします。

**Comment by ghost** [comment]
今泉さん
ご連絡が遅くなり申し訳ありません。
上記の通り実行したところ、無事処理が完了しました！
ありがとうございました！
